require('basic')
require('clipboard')
require('commands')
require('filetypes')
require('mappings')
require('plugins')
pcall(require, 'work') -- Optional work-specific configuration (gitignored)
require('gui')
