fork = true
idle = true
maximized = false
no-multigrid = false
tabs = false
title-hidden = true
frame = "buttonless"

[font]
    normal = "Terminus (TTF)"
    size = 12.0
    hinting = "none"
    edging = "antialias"
