fork = true
idle = true
maximized = true
no-multigrid = false
tabs = false
title-hidden = false
frame = "full"

[font]
    normal = "Terminus (TTF)"
    size = 8.0
    hinting = "none"
    edging = "alias"

